sudo: false
language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_33a1f872d85b_key -iv $encrypted_33a1f872d85b_iv
  -in lfpSecret85a5243a0bd4.json.enc -out lfpSecret85a5243a0bd4.json -d
install:
- echo "<Ignoring install... Enter install script here>"
script:
- echo "<Ignoring script... Enter testing script here>"
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: lfpSecret85a5243a0bd4.json
  project: learning-for-purpose
